[package]
name = "collections_datatypes"
version = "0.1.0"
authors = []

[lib]
name = "collections_datatypes"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.16.0"
rustler_codegen = "0.16.0"
lazy_static = "0.2"
